#Leia duas matrizes 4 x 4 e escreva uma terceira com os maiores valores de cada posição das matrizes
#lidas.
from random import randint


'''linha= 3
matriz1=[0]*linha
matriz2= [0]*linha
maiores= [0]*linha
maior= 0

for i in range(len(matriz1)):
    if i==0:
     matriz1[i]=[0]*linha
     matriz2[i]=[0]*linha
     maiores[i]=[0]*linha
    for t in range (len(matriz1[i])):
        matriz1[i][t]= randint(0,50)
        matriz2[i][t]= randint(0,50)
        if matriz1[i][t]
'''
